"""ETER-ViT 설정 v6_4 — VGG perceptual loss fine-tune (SS2D v6_4 와 동일 처방)."""
import os

PATH_FOLDER = 'logs/ETER_ViT_R4_brain320_v6_4/'
PATH_FOLDER = './' + PATH_FOLDER
if not os.path.exists(PATH_FOLDER):
    os.makedirs(PATH_FOLDER)

IMAGE_SIZE = (320, 320)
PATCH_SIZE = (16, 16)
INPUT_CHANNELS = 32

BATCH_SIZE = 4
NUM_EPOCHS = 50
LEARNING_RATE_ADAM = 5e-5
LR_COSINE_MIN = 5e-7
LAMBDA_REGULAR_PER_PIXEL = 3e-5
LAMBDA_SSIM_PER_PIXEL = 1.0
LAMBDA_PERCEPTUAL = 0.1

DROPOUT = 0.2
TRAIN_AUGMENT = True
TRAIN_AUGMENT_FLIP_P = 0.5

EARLYSTOP_PATIENCE = 5
VAL_EVERY_N_EPOCHS = 5

RESUME_CKPT = './logs/ETER_ViT_R4_brain320_v6/eter_vit_best.pt'

NUM_VIT_ENCODER_HIDDEN   = 384
NUM_VIT_ENCODER_LAYER    = 6
NUM_VIT_ENCODER_MLP_SIZE = 1536
NUM_VIT_ENCODER_HEAD     = 6

NUM_ETER_HORI_HIDDEN = 6
NUM_ETER_VERT_HIDDEN = 6

NUM_VIT_DECODER_HEAD               = 8
NUM_VIT_DECODER_DIM_MLP_HIDDEN     = 2048
NUM_VIT_DECODER_DIM                = 512
NUM_VIT_DECODER_DIM_HEAD           = 64
NUM_VIT_DECODER_DEPTH              = 6
NUM_VIT_DECODER_FINAL_LINEAR_OUT_CH   = 64
NUM_VIT_DECODER_FINAL_LINEAR_OUT_FEAT = 8
